#!/bin/bash

# Solicita o nome da pessoa
echo "Digite o nome completo do cliente:"
read nome
#cpf da pessoa
echo "digite o cpf"
read cpf

# Solicita o endereço da pessoa
echo "Digite o logradouro:"
read endereco

#rua 
echo "digite o nome da rua"
read rua
#numero da casa
echo "digite o numero da casa"
read num
#data do cadastro
echo "digite a data do cadastro"
read cad
# Solicita o telefone da pessoa
echo "Digite o telefone do cliente:"
read telefone

#solicita o nome que vai ser dado ao arquivo
echo "qual o nome do arquivo"
read arq
# Salva os dados em um arquivo
echo "NOME: $nome" >> arqs/cadastros/$arq.txt
echo "CPF: $cpf" >> arqs/cadastros/$arq.txt
echo "LOGRADOURO: $endereco" >> arqs/cadastros/$arq.txt
echo "RUA: $rua" >> arqs/cadastros/$arq.txt
echo "NUMERO:  $num" >> arqs/cadastros/$arq.txt
echo "TELEFONE: $telefone" >> arqs/cadastros/$arq.txt
echo "DATA DO CADASTRO: $data" >> arqs/cadastros/$arq.txt


# Mensagem de confirmação
echo "Cadastro realizado com sucesso!"
