#!/bin/bash

#Emissor de Notas

#Definindo variáveis

while :
do


if [ -d /notas/ ];
then
echo "a pasta exixte, vamos continuar."
./cfg/cr.x
else
echo "a pasta não existe, ja vou criar"
mkdir arqs/notas
sleep 3
clear
echo "pronto, pasta criada! vamos prosseguir"
fi




clear
echo -e "\033[0;33m Digite o nome do cliente: \033[0m"
read nome

echo -e "\033[0;34m Digite o valor da nota: \033[0m"
read valor

echo -e "\033[0;36m Digite a data da nota \033[0m:"
read data

#Criando arquivo

touch notas/nota-$nome.txt

#Inserindo dados

#echo "Nota Fiscal" >> nota-$nome.txt
#echo "Cliente: $nome" >> nota-$nome.txt
#echo "Valor: $valor" >> nota-$nome.txt
#echo "Data: $data" >> nota-$nome.txt

#Exibindo nota

cat notas/nota-$nome.txt
clear
sleep 2
echo -e "\033[0;32mNOTA \033[0m \033[0;35m $nome \033[0m \033[0;32mCRADA COM SUCESSO \033[0m"
sleep 5
clear
#echo -e "\033[0;31m Reiniciando o programa  \033[0m"
#echo -e "\033[0;31m precione ctrl+c para cancelar \033[0m"
sleep 5
clear
# Exibe o menu de seleção
echo "Menu de Seleção"
echo "1 - reiniciar"
echo "2 - sair"

# Lê a opção do usuário
read -p "Digite a opção desejada: " opcao

# Executa o loop enquanto a opção for diferente de 4
 [ $opcao -ne 4 ];
  case $opcao in
    1)
      echo "ok"
      ./cfg/cr.x
      ;;
    2)
      echo "saindo"
       sleep 1
       exit
      ;;
    *)
      echo "Opção inválida"
      ;;
  esac
  read -p "Digite a opção desejada: " opcao


echo "Saindo..."
done
